---
name: Vprofile actions

on: workflow_dispatch

env:
  AWS_REGION: "eu-central-1"
  ECR_REPOSITORY: "zero-dawn/vprofileapp"
  EKS_CLUSTER: "vprofile-eks"

jobs:
  Testing:
    name: Run Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Maven Test
        run: mvn test

      - name: Checkstyle
        run: mvn checkstyle:check

      # Setup java 11 to be default (sonnar scanner requires at least java 11)
      - name: Setup Java 11
        uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: '11'

      # Setup Sonar Scanner
      - name: Setup SonarQube
        uses: warchant/setup-sonar-scanner@v8
        with:
          version: 7.2.0.5079

      # Run sonar-scanner
      - name: SonarQube Scan
        run: sonar-scanner
            -Dsonar.host.url=${{ secrets.SONAR_URL }}
            -Dsonar.login=${{ secrets.SONAR_TOKEN }}
            -Dsonar.organization=${{ secrets.SONAR_ORGANIZATION }}
            -Dsonar.projectKey=${{ secrets.SONAR_PROJECT_KEY }}
            -Dsonar.sources=/src
            -Dsonar.junit.reportPaths=target/surefire-reports
            -Dsonar.jacoco.reportPaths=target/jacoco.exec
            -Dsonar.java.checkstyle.reportPaths=target/checkstyle-result.xml
            -Dsonar.java.binaries=target/test-classes/com/visalpathit/account
      
      # Check the Quality Gate status
      - name: SonarQube Quality Gate Check
        id: sonarqube-quality-gate
        uses: sonarsource/sonarqube-quality-gate-action@master
        # Forces to fail step after specification
        timeout-minutes: 5
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_URL }}
